# Generated by Django 4.0.2 on 2022-04-07 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsd_wins', models.IntegerField(default=0)),
                ('lsd_losses', models.IntegerField(default=0)),
                ('lsd_draws', models.IntegerField(default=0)),
                ('lsd_games', models.IntegerField(default=0)),
                ('lsd_elo', models.IntegerField(default=0)),
                ('lsd_winpercent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtg_wins', models.IntegerField(default=0)),
                ('mtg_losses', models.IntegerField(default=0)),
                ('mtg_draws', models.IntegerField(default=0)),
                ('mtg_games', models.IntegerField(default=0)),
                ('mtg_elo', models.IntegerField(default=0)),
                ('mtg_winpercent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mtg_duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player1_start_rating', models.IntegerField(default=1000)),
                ('player2_start_rating', models.IntegerField(default=1000)),
                ('player1_end_rating', models.IntegerField(default=1000)),
                ('player2_end_rating', models.IntegerField(default=1000)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtg_duelist1', to='login.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mtg_duelist2', to='login.player')),
            ],
        ),
        migrations.CreateModel(
            name='lsd_duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('player1_start_rating', models.IntegerField(default=1000)),
                ('player2_start_rating', models.IntegerField(default=1000)),
                ('player1_end_rating', models.IntegerField(default=1000)),
                ('player2_end_rating', models.IntegerField(default=1000)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsd_duelist1', to='login.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lsd_duelist2', to='login.player')),
            ],
        ),
    ]
